name: project1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Retro
      fonts:
        - asset: assets/fonts/retro_computer_personal_use.ttf

    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
