name: project03
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.0
  flame_audio: ^2.11.4
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.6
  webview_flutter: ^4.11.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
